### ISSUE TITLE
[api]: LGS Sync-API fails when sending duplicate `Content-Type` header values

### ISSUE THREAD

**Issue by TobyTheHutt** [ch-bj/lgs-person-data-processor-service#36]
**Describe the bug**
The issue was discovered when an Apache reverse proxy was set up between a sending batch system and the LGS processor. For whatever reason, the proxy does not correctly recognize the HTTP header `Content-Type: application/json` and adds its own duplicate of it.

This results in LGS replying with the message:
```json
{
    "timestamp":
        "2024-03-06T11:59:39.007+00:00",
        "status":415,
    "error":
        "Unsupported Media Type",
    "message":
        "Invalid mime type \"application/json, application/json\": Invalid token character ',' in token \"json, application/json\"",
    "path":
        "/api/v1/sync/partial/person-data"
}
```

**Version of LGS**:

- **LGS Version**: 2.0.4

**What happened**:
For a project, I tried to run a partial LGS sync to verify the correct configuration between our application and LGS. For networking reasons, a direct access from the batch application (sender) cannot directly access LGS, but has to go through an Apache reverse proxy instead. This resulted in the error message displayed in the bug description.

The issue does not exist without any network component between the systems, as we know this from different projects.
I did not yet analyse the outgoing traffic of our batch application, since the issue doesn't exist without proxying. Of course, I will do so if requested.

**What you expected to happen**:
I expect LGS to comply with [RFC7230](https://datatracker.ietf.org/doc/html/rfc7230#section-3.2.2) and to accept a comma separated list of MIME-Types.

**How to reproduce it** (as minimally and precisely as possible):
Just run the proposed cURL Command from the [README.md](../blob/develop/README.md) with two comma separated MIME-Types:
```shell
curl --request PUT \
--url http://<HOST>/api/v1/sync/full/trigger/start \
--header 'Authorization: token <API_KEY>' \
--header 'Content-Type: application/json, application/json'
```

**Anything else we need to know**:
A workaround for Apache is to just rewrite the Content-Type header for the according location, so only the first entry is left: `RequestHeader edit Content-Type "^application\/json\\,\ " ""`

**Comment by Ghabi-ISC** [comment]
@TobyTheHutt I don't know if I understood it correctly. But as far as I can see in the description, the LWGS Service is responding with an error to wrong input. LWGS is behaving according to standards.

Could you explain more? Is LWGS, in any way, creating this wrong header?

**Comment by TobyTheHutt** [comment]
@Ghabi-ISC sorry for being unclear. As far as I understand, the header from the error message uses a correct notation and is not wrong.

I read from the error message that the header value `application/json, application/json` is not accepted because of the containing comma (`,`), but according to [RFC7230](https://datatracker.ietf.org/doc/html/rfc7230#section-3.2.2), comma separated lists of multiple MIME types i.e. header values in general should not be an issue.

I assumed therefore that the used class (`MediaType`?) is not fully compliant with the standard. If I misread the standard or failed to consider other sources of information, let me know.

**Comment by Ghabi-ISC** [comment]
I would divide the problem into two parts:

1. What is expected:
The API supports only one content type: "application/json". Therefore any other content type, or using more than one content type could eventually lead to an error. Hence, the service is still working correctly and there is no need to change it.

2. Why are we getting the error:
This is a different story. it appears to be a bug in the underlying controller, similar to what I could find in multiple reports online. Ideally, this bug will be solved with the next upgrade of the framework.

**Comment by Ghabi-ISC** [comment]
At the moment, no fix will be provided to this bug. We will keep an eye on this behavior with the next upgrade of the stack.

**Comment by TobyTheHutt** [comment]
I agree that this is not urgent, nor solely a problem of the LGS. I will also conduct some network analysis to reconstruct how the header ends up in this way. If you want a documentation of the analysis, let me know.
